server:
  port: 9091
spring:
  mvc:
    view:
      suffix: .html
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  # Mysql DB Connection Setting
  # REF > https://velog.io/@minbo2002/JPA-application.yml-%EC%84%A4%EC%A0%95
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/KPJ?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: as2646
  # JPA Setting
  # REF >> https://mopil.tistory.com/152
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

